name: Build and push new actions on Quay.io
on:
  pull_request:

jobs:
  validation:
    runs-on: Ubuntu-20.04
    env:
      CGO_ENABLED: 0
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Show available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Show env
        run: env

      # The ./hack/action-build-and-deploy.sh runs as sudo. It means that root is the user who needs to be authenticated against quay.
      # That's why we can't use the docker-login action here.
      - name: Log in to Quay.io
        if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        run: echo "${{ secrets.QUAY_PWD }}" | sudo docker login -u ${{ secrets.QUAY_USER }} --password-stdin quay.io

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Fetch all the deps!
        run: nix-shell --run 'go get ./...'

      - name: build and deploy
        run: ./hack/action-build-and-deploy.sh
