name: For each pull request
on:
  pull_request:
  push:

jobs:
  validation:
    runs-on: Ubuntu-20.04
    env:
      CGO_ENABLED: 0
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      id: qemu
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Show available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # I opened this issue and a case on GitHub support
    # https://github.com/actions/checkout/issues/477 The support team answered
    # that right now there is not a clean way to take a diff because the
    # checkout action pulls the minimum it can.
    # I am watching this PR because it will help
    # https://github.com/actions/checkout/pull/155
    - name: fetch remote
      if: github.event.pull_request
      run: |
        git fetch origin
        git remote add upstream ${{ github.event.pull_request.head.repo.html_url }}
        git fetch upstream

    - name: Show env
      run: env

    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Generate Artifact Hub manifests
      run: make artifacthub/gen-manifests

    - name: CI checks
      run: make ci
      env:
        GITHUB_BASE_REF: ${ GITHUB_BASE_REF }
        GITHUB_HEAD_REF: ${ GITHUB_HEAD_REF }

    - name: Deploy
      if: ${{ startsWith(github.ref, 'refs/heads/main') }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./artifacthub-manifests
        publish_branch: artifacthub-manifests
        keep_files: true
